#
#
#

Install logger:
  extends: .autodevops_install
  image: node:14.16.0-alpine3.11
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
    - yarn exec yarn-workspace-focus-install
      --
      --cwd infra/logger
      --
      --frozen-lockfile --prefer-offline
  artifacts:
    expire_in: 1 week
    paths:
      - infra/logger/node_modules
      - node_modules

#
#
#

Build logger:
  extends: .base_yarn_script
  image: node:14.16.0-alpine3.11
  needs:
    - job: Install logger
      artifacts: true
  before_script:
    - cd infra/logger
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - infra/logger/lib

#
#
#

Lint logger:
  extends: .autodevops_lint
  image: node:14.16-alpine3.13
  needs:
    - job: Install logger
      artifacts: true
  before_script:
    - cd infra/logger
  script:
    - yarn lint

#
#
#

Test logger:
  extends: .autodevops_test
  image: node:14.16-alpine3.13
  needs:
    - job: Install logger
      artifacts: true
  before_script:
    - cd infra/logger
  script:
    - yarn test
  artifacts:
    expire_in: 1 week
    paths:
      - infra/logger/lib
