## Requests available:

###
GET http://localhost:8787/export?environment=production

###
GET http://localhost:8787/export?environment=preproduction

###
GET http://localhost:8787/export

###
POST http://localhost:8787/export
content-type: application/json

{
  "environment": "preproduction",
  "userId": "8babda41-6001-4665-96f5-c430fddb0c53"
}

###
GET http://localhost:8787/sitemap

###
POST http://localhost:8787/sitemap

###
POST http://localhost:8787/copy

###
POST http://localhost:8787/glossary/all

###
POST http://localhost:8787/glossary
content-type: application/json

{
  "type": "html",
  "content": "<p>Ceci est une abrogation</p>"
}
