image:
  repository: $CI_REGISTRY_IMAGE/hasura
  tag: master

deployment:
  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20

  resources:
    requests:
      cpu: 5m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1500Mi

  env:
    - name: NODE_ENV
      value: "production"
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "false"
    - name: HASURA_GRAPHQL_SERVER_PORT
      value: "80"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: "startup, http-log, webhook-log, websocket-log, query-log"
    - name: HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT
      value: 10
    - name: HASURA_GRAPHQL_NO_OF_RETRIES
      value: "5"
    - name: HASURA_GRAPHQL_ENABLE_TELEMETRY
      value: "false"
    - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
      value: "public"
    - name: ACCOUNT_EMAIL_WEBHOOK_URL
      value: http://www:3000/api/webhooks/account
    - name: PUBLICATION_WEBHOOK_URL
      value: http://www:3000/api/webhooks/publication
    - name: API_URL
      value: http://www:3000/api

  envFrom:
    - secretRef:
        name: cdtn-admin-secrets
ingress:
  enabled: false
