
# dont include restore jobs on deploys
components = ["!restore", "!sitemap-uploader","*"]
require = ["ts-node/register"]

# dont include underscores-prefix components
[environments.prod]
components = ["!(_*)"]
