plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: |
        yarn lerna version ${nextRelease.version} \
          --no-git-tag-version \
          --yes
      publishCmd: |
        yarn lerna publish from-git --yes
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - lerna.json
      - package.json
      - shared/*/CHANGELOG.md
      - shared/*/package.json
      - targets/*/CHANGELOG.md
      - targets/*/package.json
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
