version: "3.6"
services:
  postgres:
    image: postgres:10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgrespassword

  hasura:
    build:
      context: targets/hasura
    volumes:
      - ./targets/hasura/migrations:/hasura-migrations
      - ./targets/hasura/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  www:
    build:
      context: .
      dockerfile: targets/www/Dockerfile
      shm_size: 512m
    depends_on:
      - hasura
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  db_data:
