version: "3.8"
services:
  postgres:
    image: postgres:10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgrespassword

  hasura:
    build:
      context: targets/hasura
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - ./targets/hasura/migrations:/migrations
      - ./targets/hasura/metadata:/metadata
      - ./targets/hasura/config.yaml:/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"

  www:
    build:
      context: .
      dockerfile: targets/frontend/Dockerfile
      shm_size: 512m
    depends_on:
      - hasura
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_ENDPOINT: "http://hasura:8080/v1/graphql"

  contributions:
    build:
      context: .
      dockerfile: targets/contributions/Dockerfile
      shm_size: 512m
    depends_on:
      - hasura
      - www
    ports:
      - "3200:3200"
    environment:
      API_URI: http://www
    env_file:
      - .env

  ingester:
    build:
      context: .
      dockerfile: targets/ingester/Dockerfile
      shm_size: 512m
    depends_on:
      - hasura
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_ENDPOINT: "http://hasura:8080/v1/graphql"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite"
    ports:
      - "11000:10000"
      - "11001:10001"
      - "11002:10002"

volumes:
  db_data:
