import { GITLAB_LIKE_ENVIRONMENT_SLUG } from "./GITLAB_LIKE_ENVIRONMENT_SLUG";

export const PREPROD_PG_ENVIRONMENT = "preprod";
export const PG_ENVIRONMENT_SLUG = process.env.CI_COMMIT_TAG
  ? PREPROD_PG_ENVIRONMENT
  : GITLAB_LIKE_ENVIRONMENT_SLUG.replace(/-/g, "");
