apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-ingester
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 0 1 * * *
  jobTemplate: |
    {{- include "job.ingester" . | toYaml | nindent 4 }}
