apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: npm-tiptap
  namespace: cdtn-admin
spec:
  encryptedData:
    TIPTAP_AUTH_TOKEN: AgCYNRPICOxyRzp1TyuDWEhAfNrfseRqveDG5/2Q7PPnmmcPptoU/4GYCOeGf3mmXju96USLUoLGwhC3MN8FnW32kH547p0dvUXvwrrJVdxInjP9I8VXptQYPlfjjIFEs19VTj00H27DrapXEPlT4nAjAnHxeRlvtGoMR1xL3UrB2aq5v2j7w+6aY97HYqagrHYI1wkTE9vRRdzgP6wgJuI1ENswBIsVwL6LXRF/d1xxE2Rr6YANe4DXmdE7O+PNxoDzBIXw5B7ie9zNksJw8XbN22oUNzjL9AxS7Oha7XLyeLMc4/NDURhK/eqtBait/RFZNCREU6TPq/lZ90qDXZAm2CpMTk5mzNC6DftUjp9MPy+PurRoZ66HoPJocDZFEo2ZY3ERSSi8gFkwsg65mGpJBAajFgf4Ua0qH9RstlpE15O/+o42l3SvGhLnnkpjaFzz75KAvAkKIcGKMlOT9xl4Ek/HvGcKvzy3yvLCp1hlVJ6Wa/Mp3L9D8JcbXQMaCx9nXCxjEr0LHnucII5XXk4ANlddxVz6A6uWpcoz72zlfPQuOUhBp6jj0vzQQuCiQOs9w4xiuuudOGktG13vXKgMBLiW1qDxifS69fmwybQlpIc0udZ7GiothzyCT/++u8i1hJLbilmGWw1SvIYmoeYLyF3CT4Nd1p92Cz29HUbZmqs2HFORkTnHWTsM7ZbXDDeeMafyWZ0HfokZR8KO9efqa7I1oWMA1+UMXPLnieXD9AXeb1ShlxikGj5oxw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: npm-tiptap
    type: Opaque
