apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: npm
  namespace: cdtn-admin
spec:
  encryptedData:
    NPMRC: AgB09zelNQPM+hbe4fqpQFPfnFwz8U3ViSoauAcQ/dKVAHrWUcOKJ37O5x6fF0T2vJZRQUjaS0CmqpfJcp60iGm0zfI7/QW8t1h6+yeOWY+MbHQHvzKfkFI/4nX686UZDAALDd+S00A+/LwBeHUZi5E3tcWgNYq/gHo2hF7oRga4EmjzV3XLDUnRyedaVrmsTmlfEOqbhY/qVBdwnrAKuPDinDEchalJ96LwCwkkwNwBm6vaBf6BJYtM7SUZ6/Ds+bqlmXLM7X9sxeACHS36K0yR5H6XEPtizjebvtuEXGl3My4WflDfbklgmRwg0Up49Eh2R/aiTKoA2SYDZ1pQbU6drSEZVks++EriL5pQuCwrOvBJNxalgNnRPHq3v+ArWM6LuJGsz5O5ZNrqBt8fAkww3wTfTZw4oFHtdiscA1bRPc10QUrAFFyvSWnQyOx+P9axGB4AbOsTn1t9j93O4Hgnjuj48A9AFkc5jbjMzXxLyJWN8wbUTxdFWIIYP0ksYcS1uU+JPmf3wnuaxcrOVjkpWcR1AN4D2QKheu+5bsCoNLlHnXlijPSgBr1UXr4pFvo3SHp9j3XopD8wDemCHHnzkKoxipl77GUR1SO8NgAXHdHjtBFTs0e/cZewIqE5A2J+L3ijPv/4QX/EMnGM0NPORGYBYTPKNE2t5sBQUb6jAzWJR35EYcV37oBovfJZJMR/OLqiaC8F3ssw6y7vuSHqA+I7aIGHBol+2ffm9QM4rwaBL3wfmcifTd+ap5L8ip7KBbKRqY0cRWAdWhRZqBoQK3cGC7o3UmICnIg66WP0DqYvtaHqlvhMvofDa1Jw59A21AWnenXzV/v4TlFtaAh9Km4XDuBCx9l9wd9l1d5ArTYd0TaAWIO0uVdrjzNY7oVEVjr5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: npm
    type: Opaque
