kind: ConfigMap
apiVersion: v1
metadata:
  name: www
data:
  HASURA_GRAPHQL_ENDPOINT: "http://hasura/v1/graphql"
  MATOMO_SITE_ID: "27"
  MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
  NODE_ENV: "production"
  PRODUCTION: "true"
  SENTRY_DSN: "https://a5e2451c6b5840c0afa28d5e94060427@sentry.fabrique.social.gouv.fr/42"
  SMTP_URL: "smtp.tipimail.com"
  STORAGE_CONTAINER: "cdtn"
  URL_EXPORT: "http://export"
