apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-alert
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 30 1 * * *
  jobTemplate:
    {{- include "job.alert" . | nindent 4 }}
