apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cleanup-db
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 0 4 * * 6
  jobTemplate:
    {{- include "job.cleanup" . | nindent 4 }}
