kind: ConfigMap
apiVersion: v1
metadata:
  name: export-elasticsearch
data:
  HASURA_GRAPHQL_ENDPOINT: "http://hasura/v1/graphql"
  NLP_URL: "https://serving-ml.fabrique.social.gouv.fr"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  BUCKET_DEFAULT_FOLDER: "default"
  BUCKET_DRAFT_FOLDER: "draft"
  BUCKET_PUBLISHED_FOLDER: "published"
  SITEMAP_DESTINATION_FOLDER: "sitemap"
  SITEMAP_NAME: "sitemap.xml"
  AGREEMENTS_DESTINATION_FOLDER: "agreements"
  AGREEMENTS_DESTINATION_NAME: "index.json"
  SITEMAP_ENDPOINT: "http://www/api/sitemap"
  ELASTICSEARCH_INDEX_PREPROD: "cdtn-main-v2"
  ELASTICSEARCH_INDEX_PROD: "cdtn-main-v2"
  MATTERMOST_CHANNEL_EXPORT: "s-cdtn-administration-veille-preprod"
