---
apiVersion: "bitnami.com/v1alpha1"
kind: "SealedSecret"
metadata:
  annotations: &a1
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: npm
  namespace: null
spec:
  encryptedData:
    NPMRC: AgC5wPPiCBlsc6a+W7A1ZYeymkGxDF4365BNxxoH9If9iYy4AaGzInGLcChizK0uex2q6YHexE+4bus1k/W2/zdpuCozSA4T26X6kU4SbA7KLCH4P33JMQ0Wbic9ytNKOOIVSUZUPq5g3c6D12M+yP34blT8XYPKJPOQdQysJEJGR0hyy3OBZvsIiOoIdRe7u4lCiUE+cNf3xu13/LH5DqYHcgEphPQAFHbSCsES2HxIQCMES1f796MnoTqUT7jbmcZquX+uvmD/D+vrYnJeTOWPRTCTm7LrySPfC9x51ugxGvzckIRyQhV2UoqRzC4E3P3tTH+KIuKpURIcyegCi68ziaB3Snuzp0A7VdpGwvbFCCjBNZ1BQw9XtZ6u19TlCvAYA3Kp6ZCovuq08IEoNUHoFX7ozp/evkgnzxJUCFOjBIOWwulant/TgVs9FJ37GUbLqiLzFvq6aIcMb5W8H6HYWQdtMxk94qUfbVwpjWwsQGT/SsKYKWHS47hbchEc8cvPB66wQlxqda9a+s3N3SLqqi2K6AJDQJnbsEI2jyAZ2NsRGmlzkp6wMGRmFALEHpFReBL7Sp5p4Ajy4y71I3KqVOJ1TnPAvfDo58EIHBaJv7nfNXpBgLf3QL1+uHV/36KvBj0Z2M9coQNRjyVW5U7gVKT7+usjFuQLP+gLRjs4xSBhmaUtr0PMvWK7dKcNRa0S8rTLPZkYdcOgSR40X6g5EGYP8gCbasdjxpSgmrwRZ4g96VRJioQxxf6Y5hfBNFgyFY+HFxk3lXQDUTo+p5fZqKrt6S5treYU/Yx5PMfWRLD0FMKXCka7P1dU7akXK9jSt6QXwMS9fUH+YHR/EStL+HPaSa+25CihSJZETrqikQ31qqa0MxTr3+TpYYKfxXKQeJDB
  template:
    metadata:
      annotations: *a1
      name: npm
    type: "Opaque"
