apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: www
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgAObcZKrO3zRrVCfoXEAntOXyZlHFJdxUep4iWbQdITqzDw32DhJzynwXmLTlOcJrAf0acuDOK3xMoOH2QZO4EaDOmpL8vJwmvQWIccdO/Gll2cxwCr/Cbu/9RmMixaXtrscoPz7m2geO5u/0dRCFE5IVUGZfaOBY+zHIFaxPFxWu9edjHWS9JJfRqcIoEyCLudmM1N20UGa2fq1tuIbD5ZS9f392l3669wqRB4tNnKxOKIJEQ4GA5PkqYYLoFsGGtAR5Hw9/eweXP0KXZfQjRJUfowdzFsx3wutjd2PVz7t0K5WZc2X4+RsodhEEYZJD013vXSQBHm8u/0VHQwAWotNt2uVoAbvVzup3DvqxUBN5LJIRanmFHTw2JNh+s4eUvd+86PBiTpoPXIg9QpGWy4rhG7gJ614HOD70cLL6jik48Ezbi4OfOBQGKbs0rrkPiAg60jCW4wXgQqpdH+6TEj/z7+/ZU0um5pKTUA6DS8EN5xU1xQdHLMo7WVXQHI26lbWRtLMQA8JYmvq/kXfhcH6kYVERDWYK1QiajGSdDbEGkjxDh0Uk8KRHAtBw2xXgT8lV6wpVIuGrrc1B6CbJOGgEBUwdjbD9v7n4mqAEp7N8d6Gsc0Nbsc2rrAl4rVB7/ihoUXEtQthrXA8UFj8p7f/O7AMKXCU8gt29FeTFNEwydXhXw1EPlfUzr4/Gp3uNXiLSpjK9/3F4jQMAOHz64XOipFPMxncZSXounxVGJT8yBhxYEvpUq/9nufFA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: www
    type: Opaque
