jobs:
  runs:
    build-frontend:
      with:
        buildArgs:
          NEXT_PUBLIC_BASE_PATH: https://cdtn-admin.fabrique.social.gouv.fr

www:
  autoscale:
    enabled: true
  host: cdtn-admin.fabrique.social.gouv.fr
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 185.24.184.196,185.24.185.196,185.24.186.196,185.24.187.196,185.24.187.254,164.131.160.1,164.131.160.2,164.131.160.3,164.131.160.4,164.131.160.5,164.131.160.6,164.131.160.17,164.131.160.18,164.131.160.19,164.131.160.20,164.131.160.21,164.131.160.22,164.131.160.33,164.131.160.34,164.131.160.35,164.131.160.36,164.131.160.37,164.131.160.38,164.131.160.49,164.131.160.50,164.131.160.51,164.131.160.52,164.131.160.53,164.131.160.54,45.80.34.219
  env:
    - name: NEXTAUTH_URL
      value: https://cdtn-admin.fabrique.social.gouv.fr
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "386Mi"

export:
  replicas: 1
  resources:
    limits:
      cpu: "2000m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "2Gi"

hasura:
  autoscale:
    enabled: true
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "768Mi"
  envFrom:
    - secretRef:
        name: pg-app
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
  backup:
    name: 2024-03-26-12-33
  cnpg-cluster:
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 2Gi
