www:
  autoscale:
    enabled: true
  host: cdtn-admin.fabrique.social.gouv.fr
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 185.24.184.196,185.24.185.196,185.24.186.196,185.24.187.196,185.24.187.254,164.131.160.1,164.131.160.2,164.131.160.3,164.131.160.4,164.131.160.5,164.131.160.6,164.131.160.17,164.131.160.18,164.131.160.19,164.131.160.20,164.131.160.21,164.131.160.22,164.131.160.33,164.131.160.34,164.131.160.35,164.131.160.36,164.131.160.37,164.131.160.38,164.131.160.49,164.131.160.50,164.131.160.51,164.131.160.52,164.131.160.53,164.131.160.54,90.63.199.50,92.159.11.30
  env:
    - name: NEXTAUTH_URL
      value: https://cdtn-admin.fabrique.social.gouv.fr
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "386Mi"

export:
  replicas: 1
  resources:
    limits:
      cpu: "2000m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "2Gi"

hasura:
  autoscale:
    enabled: true
  resources:
    limits:
      cpu: "1500m"
      memory: "2.5Gi"
    requests:
      cpu: "500m"
      memory: "1.5Gi"
  envFrom:
    - secretRef:
        name: pg-superuser
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura
  env:
    - name: "HASURA_GRAPHQL_DATABASE_URL"
      value: "postgresql://$(username):$(password)@$(host):$(port)/cdtn-admin?sslmode=require"
  annotations:
    oblik.socialgouv.io/min-request-cpu: "500m"
    oblik.socialgouv.io/min-request-memory: "1.5Gi"
    oblik.socialgouv.io/min-limit-cpu: "1500m"
    oblik.socialgouv.io/min-limit-memory: "2.5Gi"

pg:
  cnpg-cluster:
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 2Gi
  backup:
    name: 2024-03-26-12-33
  annotations:
    oblik.socialgouv.io/min-request-cpu: "1"
    oblik.socialgouv.io/min-request-memory: "2Gi"
    oblik.socialgouv.io/min-limit-cpu: "2"
    oblik.socialgouv.io/min-limit-memory: "2Gi"
