Install alert:
  extends: .autodevops_install
  image: node:12.18.0-alpine3.11
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/yarn
    - npx @socialgouv/yarn-workspace-focus-install --cwd targets/alert
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert/node_modules
      - node_modules

#
#
#

Build alert:
  extends: .base_yarn_script
  image: node:12.18.0-alpine3.11
  needs:
    - job: Install alert
      artifacts: true
  before_script:
    - cd targets/alert
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert/dist

#
#
#

Register alert:
  extends: .autodevops_register_image
  dependencies: null
  needs:
    - job: Build alert
      artifacts: true
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f ./targets/alert/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/alert

#
#
#

.deploy_alert_stage:
  script:
    - echo "kubectl config set-context --current --namespace=${K8S_NAMESPACE}"
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - envsubst < targets/alert/.k8s/alert.cronjob.yaml | kubectl apply -f -

Deploy alert (dev):
  extends:
    - .autodevops_deploy_app_dev
    - .deploy_alert_stage

Deploy www (prod):
  extends:
    - .autodevops_deploy_app_prod
    - .deploy_alert_stage
  variables:
    PRODUCTION: "true"
