apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: cdtnadminprodserver-backup-credentials
  namespace: cdtn-admin
spec:
  encryptedData:
    azurestorageaccountkey: >-
      AgCVj5vWPZOMIT1FZ4hD/KzBIafbvESag4ogSLtdQjCG8ZNBUQPHUe+h2OoNWBjDlNLaRAd9Dsn5lxLmtsi53+1K8pbn97vXCy+izahR8e1boo6DgMsPzKbvqxXaraAR53mZYw0+ywyTyiMG+9uHX2f6iehVfS1FkNA/fLBFp1dF+oTYO5x3oYii2lndLVvG3vhItsIvzbdUcSvQEt0ybjPIqxD3eqvWxVgDkDgt3jbSwtIDhGMSuJDP2KOOKb6kVDX8AqVFtZibDcyuAZ8SUM9AM3YMjjCML4Hi2pQXFV/vnTQDoKa1S+scMZFmExFJ6s6H8U79Ib3gy4w6Nq7JTAIvFFJDlCLy1YK9PYnG36tqpMBbUB+/fPwXsHXA6RBLnjO4BjifqRSAbmed0uy4/QWsemk4eHaKCqRCS4Zw6bzI0GrAV2euvEE/Q/XGffnbmCp4tfZgTi+GWlrCZCdJJCyW259mdjKPJutdIj9w/TwAXLZ0cs1fxA87Q7lio1WPYSYfVW96RYtTugjaDfDjxNnpKjYnkKXkymbYVvYY6Vc/Eplink+WD3NTV4xILy/OQrDp67v42vHHDY7mzL5paNzw5o7dHNoYUjxj7Yz+6xGTHNedkwWfBEjkbH+UW5VZ7j0+UAQpLDh+BvpsuHF1MnHRRki8ePcKe31AddJcNjRF8rHpmmdaxq1nw0nxTZgMgx6D2skG0Nx4Dh13ZcPoBcLyTKk/ZCiOZTImcHQkqAKfW1xSud7PCx0tXXh66myhAeWhr6ptRGJJKFXI9mVaHKKOeQH9bcJNuOCWuh2nUPkZOIL3F8kXhaCK
    azurestorageaccountname: >-
      AgBmOUme/CM1ORvvlOTvQgYoV/Dz/NmFrB4/+7Mt6sLCbJ+RPWDlNlC7LPNPp/hZ7p9QghPTfNxYIHpTIfsaPIsl90csdGvxemOM5OGfbO7HXhRHcWBNLrfptpLR9k9UVLfdqEogcNd7hZy8I5BvCoPOw92U7hPkSSxT4nGm8pmAeSykk3E9uPfW5gur6UbiTFw12NRZKc3cDhdpE3Jk+nrXvbrISyK/Ss4AY+KA3ROI+lKxXEONPdUAurmct2O2fPxYoxbbKShHZKkaB5upaDs9Cn2ikDwhck3aeh6YxyiRpXVaAOVNE0Sq+mqVmWtPVya3mVh3FAa6Tk9YISn6G9oRoFP2Q8hzOTqJFLopmpFlSRxpQkW5shXQ+kU27uYKnFaZVjRkTncICV1PFHSmOZs5pkZJFjFn97DHDRJLQ0lhOn9NcE5FTCR45pFonYp7v2jg2icWxaCYgCZPre6t37z1FnBDGTptPn5ZtJIWvzw1OO8koiKgZ5cMuw3Yh3jDUmj8C4yxrY4mhWFSH9vOfHOWkyhAQpxKh8Dcp+yvIEFjl4X0BVu9aHQqROWdy+3uult1TjTYWdLx1ZOlzuT8sO6DdNSc4g0dI+0NvUEd3m6ZFnmCFiVUpYiP5+gljg/e7ha3XJs93n3pg3ip6ucaqFfQfWmHYzDYjT64UkperyS50u4c4145wRI+N89tT4umCXpUKLJg2ETQnsQUmes3a+oTrAzX6A==
  template:
    metadata:
      annotations: {}
      name: cdtnadminprodserver-backup-credentials
    type: Opaque
