ARG NODE_VERSION=14.18.0-alpine3.11

# dist
FROM node:$NODE_VERSION AS dist

WORKDIR /

COPY ./package.json /

RUN yarn

COPY . /

RUN yarn workspace frontend build

# app
FROM node:$NODE_VERSION

WORKDIR /app

COPY --from=dist ./dataset/suggestions.txt /app/dataset/
COPY --from=dist ./package.json /app/
COPY --from=dist ./bin/ /app/bin

USER 1000

ENV NODE_ENV=production

# RUN chown -R node:node /app


CMD ["yarn", "start"]





