Install alert:
  extends: .autodevops_install
  image: node:12.18.0-alpine3.11
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/yarn
    - npx @socialgouv/yarn-workspace-focus-install --cwd targets/alert-cli
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert-cli/node_modules
      - node_modules

#
#
#

Build alert:
  extends: .base_yarn_script
  image: node:12.18.0-alpine3.11
  needs:
    - job: Install alert
      artifacts: true
  before_script:
    - cd targets/alert-cli
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert-cli/dist

#
#
#

Register alert:
  extends: .autodevops_register_image
  dependencies: null
  needs:
    - job: Build alert
      artifacts: true
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f ./targets/alert-cli/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/alert

#
#
#

.deploy_alert_stage:
  script:
    - echo "kubectl config set-context --current --namespace=${K8S_NAMESPACE}"
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - envsubst < targets/alert-cli/.k8s/alert.cronjob.yaml | kubectl apply -f -

Deploy alert (dev):
  extends:
    - .autodevops_deploy_app_dev
    - .deploy_alert_stage

Deploy alert (prod):
  extends:
    - .autodevops_deploy_app_prod
    - .deploy_alert_stage
  variables:
    PRODUCTION: "true"

#
#
#

.trigger_alert_cron:
  when: manual
  script:
    - echo "kubectl config set-context --current --namespace=${K8S_NAMESPACE}"
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - JOB_NAME="triggered-from-job-${CI_JOB_ID}-${RANDOM}"
    - kubectl create job --from=cronjob/alert "${JOB_NAME}"

    - timeout 15m
      bash -c "
      until
      kubectl get pod -l job-name=${JOB_NAME}
      -o jsonpath='{.items[0].status.conditions[?(@.type=="ContainersReady")].status}' |
      grep True
      ; do sleep 1; done"

    - kubectl logs -f job/${JOB_NAME}

    - kubectl get jobs ${JOB_NAME} -o jsonpath='{.status.conditions}'
    - kubectl get jobs ${JOB_NAME} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}'

Trigger alert (dev):
  extends:
    - .autodevops_deploy_app_dev
    - .trigger_alert_cron

Trigger alert (prod):
  extends:
    - .autodevops_deploy_app_prod
    - .trigger_alert_cron
