⚓ alert:
  extends:
    - .autodevops_install
    - .cdtn_base_rules
  image: node:14.16.0-alpine3.11
  cache:
    key: ${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache
  variables:
    CACHE_COMPRESSION_LEVEL: fastest
    CACHE_FALLBACK_KEY: ${CI_JOB_NAME}-${CI_DEFAULT_BRANCH}
    FF_USE_FASTZIP: "true"
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
    - yarn exec yarn-workspace-focus-install
      --
      --cwd targets/alert-cli
      --
      --frozen-lockfile --prefer-offline
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert-cli/node_modules
      - node_modules

#
#
#

🧪 alert:
  extends:
    - .autodevops_test
    - .cdtn_base_rules
  needs:
    - job: ⚓ alert
      artifacts: true
  before_script:
    - cd targets/alert-cli

🧻 alert:
  extends:
    - .autodevops_lint
    - .cdtn_base_rules
  needs:
    - job: ⚓ alert
      artifacts: true
  before_script:
    - cd targets/alert-cli

#
#
#

🎯 alert:
  extends: .base_yarn_script
  interruptible: true
  image: node:14.16.0-alpine3.11
  needs:
    - job: ⚓ alert
      artifacts: true
  before_script:
    - cd targets/alert-cli
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - targets/alert-cli/dist

#
#
#

🗃 alert:
  extends: .autodevops_register_image
  interruptible: true
  dependencies: null
  needs:
    - job: 🎯 alert
      artifacts: true
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f ./targets/alert-cli/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/alert
#
#
#

# .trigger_alert_cron:
#   when: manual
#   script:
#     - echo "kubectl config set-context --current --namespace=${K8S_NAMESPACE}"
#     - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
#     - JOB_NAME="triggered-from-job-${CI_JOB_ID}-${RANDOM}"
#     - kubectl create job --from=cronjob/alert "${JOB_NAME}"

#     - timeout 15m
#       bash -c "
#       until
#       kubectl get pod -l job-name=${JOB_NAME}
#       -o jsonpath='{.items[0].status.conditions[?(@.type==\"ContainersReady\")].status}' |
#       grep True
#       ; do sleep 1; done"

#     - kubectl logs -f job/${JOB_NAME}

#     - kubectl get jobs ${JOB_NAME} -o jsonpath='{.status.conditions}'
#     - kubectl get jobs ${JOB_NAME} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}'

# Trigger alert (dev):
#   extends:
#     - .autodevops_deploy_app_dev
#     - .trigger_alert_cron
#   environment:
#     name: ${CI_COMMIT_REF_SLUG}-dev2

# Trigger alert (prod):
#   extends:
#     - .autodevops_deploy_app_prod
#     - .trigger_alert_cron
#   environment:
#     name: prod2
