ARG NODE_VERSION=14.18.0-alpine3.11

# dist
FROM node:$NODE_VERSION AS dist

WORKDIR /

COPY . /

RUN yarn --frozen-lockfile

RUN yarn workspace alert-cli build

# app
FROM node:$NODE_VERSION

WORKDIR /app

COPY --from=dist targets/alert-cli/package.json /app/
COPY --from=dist targets/alert-cli/dist/ /app/dist

USER 1000

ENV NODE_ENV=production

CMD ["yarn", "start"]





