hasura:
  imagePackage: hasura
  ~needs: [post-restore, build-hasura]
  ~preDeploy.cleaner:
    match:
      kind: Deployment
    value: true
  envFrom:
    - secretRef:
        name: pg-app
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura

www:
  host: cdtn-admin-preprod.ovh.fabrique.social.gouv.fr
  env:
    - name: "FRONTEND_HOST"
      value: cdtn-admin-preprod.ovh.fabrique.social.gouv.fr

pg:
  ~chart: pg
  # force this PG cluster to be destroyed/recreated on redeploys
  ~preDeploy.cleaner:
    match:
      kind: Cluster
    value: true
  cnpg-cluster:
    backup:
      # don't enable backup because we would need a new path each time as the cluster is recreated
      ~tpl~enabled: "false"
    recovery:
      enabled: true

jobs:
  runs:
    post-restore:
      ~needs: [pg]
      use: psql
      with:
        sqlFile: .kontinuous/sql/post-restore.sql
        pgSecretRefName: pg-app
    job-ingester:
      ~needs: [hasura]
      use: trigger-cronjob
      with:
        cronJobName: cron-ingester
    job-alert:
      ~needs: [job-ingester]
      use: trigger-cronjob
      with:
        cronJobName: cron-alert
