kind: ConfigMap
apiVersion: v1
metadata:
  name: export-elasticsearch
data:
  CDTN_ADMIN_ENDPOINT: "http://hasura/v1/graphql"
  NLP_URL: "https://serving-ml.fabrique.social.gouv.fr"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
