app-www:
  host: cdtn-admin.fabrique.social.gouv.fr
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 42.0.0.0/8,185.24.186.196/32
  env:
    - name: "FRONTEND_HOST"
      value: https://cdtn-admin.fabrique.social.gouv.fr
