hasura:
  imagePackage: cdtn-admin-hasura
  needs: [seed]
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura

jobs:
  runs:
    create-db:
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    restore:
      needs: [create-db]
      use: SocialGouv/kube-workflow/jobs/restore-db
      with:
        mountPath: /mnt/restore
        restorePath: "${LATEST}/hasura_prod_db.psql.gz"
        pgAdminSecretRefName: azure-pg-admin-user
      volumeMounts:
        - name: restore
          mountPath: /mnt/restore
          readOnly: true
      volumes:
        - name: restore
          persistentVolumeClaim:
            claimName: cdtn-admin-backup-restore
    seed:
      needs: [restore]
      use: SocialGouv/kube-workflow/jobs/seed-db
      with:
        seedPath: /workspace/.kube-workflow/sql/post-restore.sql
