#
#
#

Build module/ingester:
  extends: .autodevops_install
  image: node:14.16.0-alpine3.11
  needs:
    - job: Build logger
      artifacts: true
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
    - yarn exec yarn-workspace-focus-install
      --
      --cwd shared/elasticsearch-document-adapter
      --
      --frozen-lockfile --prefer-offline
    #
    # NOTE(douglasduteil): group a pipeline in one job
    # To avoid a lenghy pipeline we do all the tasks here...
    #
    - cd shared/elasticsearch-document-adapter
    #
    #
    #
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - shared/elasticsearch-document-adapter/lib
