apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alert
  labels:
    app.kubernetes.io/part-of: ${CI_PROJECT_NAME}
    owner: ${CI_PROJECT_NAME}
    team: ${CI_PROJECT_NAME}
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: update-alert
              image: ${CI_REGISTRY_IMAGE}/alert:${IMAGE_TAG}
              resources:
                requests:
                  cpu: 1500m
                  memory: 1.5Gi
                limits:
                  cpu: 2000m
                  memory: 2Gi
              workingDir: /app
              env:
                - name: PRODUCTION
                  value: "${PRODUCTION}"
                - name: GRAPHQL_ENDPOINT
                  value: "http://hasura-cdtn-admin/v1/graphql"
              envFrom:
                - secretRef:
                    name: cdtn-admin-secrets
              volumeMounts:
                - name: data
                  mountPath: "/app/data"

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            supplementalGroups:
              - 1000
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: alert-data
          restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
