apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alert
  labels:
    app.kubernetes.io/part-of: ${CI_PROJECT_NAME}
    owner: ${CI_PROJECT_NAME}
    team: ${CI_PROJECT_NAME}
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: update-alert
              image: ${CI_REGISTRY_IMAGE}/alert:${IMAGE_TAG}
              resources:
                requests:
                  cpu: 1500m
                  memory: 2.5Gi
                limits:
                  cpu: 2000m
                  memory: 3Gi
              workingDir: /app
              env:
                - name: PRODUCTION
                  value: "${PRODUCTION}"
                - name: HASURA_GRAPHQL_ENDPOINT
                  value: "http://hasura/v1/graphql"
              envFrom:
                - secretRef:
                    name: cdtn-admin-secrets
              volumeMounts:
                - name: tz-paris
                  mountPath: "/etc/localtime"

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            supplementalGroups:
              - 1000
          volumes:
            - name: tz-paris
              hostPath:
                path: /usr/share/zoneinfo/Europe/Paris
          restartPolicy: Never
