#
#
#

Install www:
  extends: .autodevops_install
  image: node:12.18.0-alpine3.11
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/yarn
    - npx @socialgouv/yarn-workspace-focus-install --cwd targets/www
  artifacts:
    expire_in: 1 week
    paths:
      - "shared/*/node_modules"
      - targets/www/node_modules
      - node_modules

#
#
#

Build www:
  extends: .autodevops_build
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - targets/www/.next/cache
  dependencies: null
  needs:
    - job: Install www
      artifacts: true
  variables:
    # these variables are needed at build time because embedded in the front
    NEXT_PUBLIC_SENTRY_DSN: https://yyy@sentry.fabrique.social.gouv.fr/yyy
    NEXT_PUBLIC_MATOMO_URL: https://matomo.io
    NEXT_PUBLIC_MATOMO_SITE_ID: 4242
  before_script:
    - cp .env targets/www/.env.production
    - cd targets/www
  artifacts:
    expire_in: 1 week
    paths:
      - targets/www/.next

Test www:
  extends: .autodevops_test
  dependencies: null
  needs:
    - job: Install www
      artifacts: true
  before_script:
    - cd targets/www

Lint www:
  extends: .autodevops_lint
  dependencies: null
  needs:
    - job: Install www
      artifacts: true
  before_script:
    - cd targets/www

#
#
#

Register www:
  extends: .autodevops_register_image
  dependencies: null
  needs:
    - job: Build www
      artifacts: true
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f targets/www/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/www

#
#
#

.deploy_www_stage:
  variables:
    PORT: 3000
    CONTEXT: www
    VALUES_FILE: targets/www/.k8s/www.values.yml
  after_script:
    - find ${MANIFEST_FOLDER} -name '*.yaml' -exec
      echo '---' \; -exec cat {} \; |
      envsubst >> manifest.yaml
    - kubectl apply --namespace=${K8S_NAMESPACE} -f manifest.yaml

Deploy www (dev):
  extends:
    - .autodevops_deploy_app_dev
    - .deploy_www_stage
  variables:
    MANIFEST_FOLDER: targets/www/.k8s/environments/dev

Deploy www (prod):
  extends:
    - .autodevops_deploy_app_prod
    - .deploy_www_stage
  variables:
    MANIFEST_FOLDER: targets/www/.k8s/environments/prod
