extends:
  - "@socialgouv/eslint-config-typescript"
rules:
  "@typescript-eslint/consistent-type-definitions": "off"
  "@typescript-eslint/naming-convention": "off"
  "@typescript-eslint/no-invalid-this": "off"
  "@typescript-eslint/no-unsafe-argument": "off"
  "@typescript-eslint/no-unsafe-return": "off"
  "@typescript-eslint/no-redundant-type-constituents": "off"
  "@typescript-eslint/no-explicit-any": "warn"
