Install ingester:
  extends: .autodevops_install
  image: node:14.7.0-alpine3.11
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/yarn
    - npx @socialgouv/yarn-workspace-focus-install --cwd targets/ingester
  artifacts:
    expire_in: 1 week
    paths:
      - targets/ingester/node_modules
      - node_modules

#
#
#

Build ingester:
  extends: .base_yarn_script
  image: node:14.7.0-alpine3.11
  needs:
    - job: Install Ingester
      artifacts: true
  before_script:
    - cd targets/ingester
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - targets/ingester/dist
