ARG NODE_VERSION=14.18.0-alpine3.11

# dist
FROM node:$NODE_VERSION AS dist

WORKDIR /

COPY targets/ingester/package.json /

RUN yarn install

COPY . /

RUN yarn workspace frontend build

# app
FROM node:$NODE_VERSION

WORKDIR /app

COPY --from=dist targets/ingester/dist/ /app/dist

USER 1000

ENV NODE_ENV=production

# RUN chown -R node:node /app


CMD ["yarn", "start"]





