app-www:
  probesPath: /healthz
  imagePackage: cdtn-admin-frontend
  envFrom:
    - configMapRef:
        name: www
    - secretRef:
        name: www
  env:
    - name: "FRONTEND_HOST"
      value: "{{.Values.global.host}}"
  ingress:
    annotations:
      "nginx.ingress.kubernetes.io/whitelist-source-range": "123.456.456.789,42.0.0.0/8"
  resources:
    limits:
      cpu: "1000m"
      memory: "560Mi"
    requests:
      cpu: "5m"
      memory: "128Mi"

app-export:
  ingress:
    enabled: false
  imagePackage: "cdtn-admin-export-elasticsearch"
  envFrom:
    - configMapRef:
        name: "export-elasticsearch"
    - secretRef:
        name: "export-elasticsearch"

hasura:
  needs: [seed]
  imagePackage: cdtn-admin-hasura
  envFrom:
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura

