app-www:
  probesPath: /healthz
  imagePackage: cdtn-admin-frontend
  envFrom:
    - configMapRef:
        name: www
    - secretRef:
        name: www
  env:
    - name: "FRONTEND_HOST"
      value: "{{.Values.global.host}}"
  resources:
    limits:
      cpu: "1000m"
      memory: "560Mi"
    requests:
      cpu: "5m"
      memory: "128Mi"

app-contributions:
  probesPath: /
  imagePackage: cdtn-admin-contributions
  containerPort: 3200
  envFrom:
    - configMapRef:
        name: contributions
    - secretRef:
        name: contributions
  resources:
    limits:
      cpu: "1000m"
      memory: "560Mi"
    requests:
      cpu: "5m"
      memory: "128Mi"

app-export:
  probesPath: /healthz
  ingress:
    enabled: false
  imagePackage: "cdtn-admin-export-elasticsearch"
  containerPort: 8787
  envFrom:
    - configMapRef:
        name: "export-elasticsearch"
    - secretRef:
        name: "export-elasticsearch"
  resources:
    limits:
      cpu: '2000m'
      memory: 2Gi
    requests:
      cpu: '5m'
      memory: 128Mi

hasura:
  imagePackage: cdtn-admin-hasura
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: azure-pg-user
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura
