Install scripts:
  extends: .autodevops_install
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - yarn
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/yarn
    - yarn --cwd scripts --frozen-lockfile
  artifacts:
    expire_in: 1 week
    paths:
      - scripts/node_modules

#
#
#

Build scripts:
  extends: .base_yarn_script
  needs:
    - job: Install scripts
      artifacts: true
  script:
    # HACK(douglasduteil): move scripts/node_modules to root
    # Ensure that all the sources in the repo can access to the installed node_modules
    # Avoid unresolved dependencies for `../src` files
    - mv scripts/node_modules node_modules

    - yarn --cwd scripts build
  artifacts:
    expire_in: 1 week
    paths:
      - scripts/dist

#
#
#

Register scripts:
  extends: .autodevops_register_image
  dependencies: null
  needs:
    - job: Build scripts
      artifacts: true
  variables:
    CONTEXT: ./
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f ./scripts/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/scripts
