#
#
#

📦 logger:
  extends:
    - .autodevops_install
    - .cdtn_base_rules
  stage: .pre
  needs: []
  image: node:14.16.0-alpine3.11
  cache:
    key: ${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache
  variables:
    CACHE_COMPRESSION_LEVEL: fastest
    # CACHE_FALLBACK_KEY: ${CI_JOB_NAME}-${CI_DEFAULT_BRANCH}
    CACHE_FALLBACK_KEY: ${CI_JOB_NAME}-alpha
    FF_USE_FASTZIP: "true"
  script:
    - yarn config set cache-folder ${CI_PROJECT_DIR}/.cache/yarn
    - yarn global add @socialgouv/yarn-workspace-focus-install
    - yarn exec yarn-workspace-focus-install
      --
      --cwd shared/logger
      --
      --frozen-lockfile --prefer-offline
    #
    # NOTE(douglasduteil): group a pipeline in one job
    # To avoid a lenghy pipeline we do all the tasks here...
    #
    - cd shared/logger
    #
    #
    #
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - shared/logger/lib
