# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/charts/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app
---
image:
  repository: $CI_REGISTRY_IMAGE/www
  tag: master

fullnameOverride: www

deployment:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

  livenessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15

  env:
    - name: AZURE_STORAGE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: azure-cdtnadmindev-volume
          key: azurestorageaccountkey
    - name: AZURE_STORAGE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: azure-cdtnadmindev-volume
          key: azurestorageaccountname

  envFrom:
    - configMapRef:
        name: www-env
    - secretRef:
        name: cdtn-admin-secrets
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
