# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/charts/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app
---
image:
  repository: $CI_REGISTRY_IMAGE/www
  tag: master

fullnameOverride: www

deployment:
  resources:
    requests:
      cpu: 5m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

  livenessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    path: /health
    periodSeconds: 15

  envFrom:
    - configMapRef:
        name: www-env
    - secretRef:
        name: cdtn-admin-secrets
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: 109.221.140.106,185.24.184.196,185.24.185.196,185.24.186.196,185.24.187.196,45.87.212.184,54.216.19.70,86.247.251.159,90.52.73.222,86.247.227.133,90.119.197.249,78.193.26.225,90.92.100.236,51.11.226.128
