projectName: cdtn
dependencies:
  fabrique:
    extends:
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                cdtnadminprodserver-backup-credentials:
                  env: [dev, preprod]
                  required: true
                cdtn-admin-prod-backups-access-key:
                  env: [prod]
                  required: true
                cdtn-admin-dev-backups-access-key:
                  env: [dev, preprod]
                  required: true
