global:
  pgUser: cdtn-admin
  pgDatabase: cdtn-admin

jobs:
  ~chart: jobs
  runs:
    build-frontend:
      use: build
      with:
        imagePackage: frontend
        dockerfile: targets/frontend/Dockerfile
        secrets:
          npmTiptapToken:
            secretName: npm-tiptap
            secretKey: NPM_TIPTAP_TOKEN
    build-ingester:
      use: build
      with:
        imagePackage: ingester
        dockerfile: targets/ingester/Dockerfile
    build-alert:
      use: build
      with:
        imagePackage: alert
        dockerfile: targets/alert-cli/Dockerfile
    build-export:
      use: build
      with:
        imagePackage: export
        dockerfile: targets/export-elasticsearch/Dockerfile
    build-contributions:
      use: build
      with:
        imagePackage: contributions
        dockerfile: targets/contributions/Dockerfile
        buildArgs:
          NODE_ENV: production
          CDTN_API_URL: https://cdtn-api.fabrique.social.gouv.fr
    build-hasura:
      use: build
      with:
        imagePackage: hasura
        context: targets/hasura

pg:
  ~chart: pg

www:
  ~chart: app
  ~needs: [build-frontend]
  probesPath: /healthz
  imagePackage: frontend
  envFrom:
    - configMapRef:
        name: www
    - secretRef:
        name: www
    - secretRef:
        name: s3
  env:
    - name: "FRONTEND_HOST"
      value: "{{.Values.global.host}}"
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  replicas: 1
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

contributions:
  ~chart: app
  ~needs: [build-contributions]
  probesPath: /
  imagePackage: contributions
  containerPort: 3200
  envFrom:
    - configMapRef:
        name: contributions
    - secretRef:
        name: contributions
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  replicas: 1
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

export:
  ~chart: app
  ~needs: [build-export]
  probesPath: /healthz
  ingress:
    enabled: false
  imagePackage: export
  containerPort: 8787
  envFrom:
    - configMapRef:
        name: export-elasticsearch
    - secretRef:
        name: export-elasticsearch
    - secretRef:
        name: s3
  resources:
    limits:
      cpu: "100m"
      memory: 256Mi
    requests:
      cpu: "50m"
      memory: 128Mi
  replicas: 1
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

hasura:
  ~chart: hasura
  ~needs: [build-hasura]
  imagePackage: hasura
  ingress:
    enabled: false
  envFrom:
    - secretRef:
        name: azure-pg-user
    - configMapRef:
        name: hasura
    - secretRef:
        name: hasura
  replicas: 2
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "50m"
      memory: 650Mi
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001

deactivate:
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true
