-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."agreements" add column "is_supported" boolean
--  not null default 'false';
