#
#
#

⚓ www:
  extends:
    - .cdtn_base_focus_install
  variables:
    PACKAGE: frontend

#
#
#

🧪 www:
  extends:
    - .autodevops_test
    - .cdtn_base_rules
  needs:
    - job: ⚓ www
      artifacts: true
  before_script:
    - cd targets/frontend

🧻 www:
  extends:
    - .autodevops_lint
    - .cdtn_base_rules
  needs:
    - job: ⚓ www
      artifacts: true
  before_script:
    - cd targets/frontend

#
#
#

🎯 www:
  extends:
    - .base_yarn_build_next
    - .cdtn_base_rules
  before_script:
    - cd targets/frontend
  needs:
    - job: ⚓ www
      artifacts: true
  artifacts:
    expire_in: 1 week
    paths:
      - targets/frontend/.next

#
#
#

🗃 www:
  extends:
    - .autodevops_register_image
    - .cdtn_base_rules
  needs:
    - job: 🎯 www
      artifacts: true
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 512M
      -f targets/frontend/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/www
