-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "contribution"."answers" add column "message_block_generic_no_CDT" text
--  null;
