#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lerna run \
  --concurrency 1 \
  --exclude-dependents \
  --parallel precommit \
  --since HEAD \
  --stream \
  ;

if git diff --cached --name-only | grep --quiet ".k8s"
then
  yarn k8s
  yarn k8s precommit
  git add .k8s
fi
