#!/bin/sh
. "$(dirname $0)/_/husky.sh"

yarn lerna run \
  --parallel prepush \
  --since origin/alpha \
  --stream \
  ;

if git diff origin/alpha --name-only | grep --quiet ".k8s"
then
  yarn k8s
  yarn k8s prepush
fi
