kind: ConfigMap
apiVersion: v1
metadata:
  name: export-elasticsearch
data:
  CDTN_ADMIN_ENDPOINT: "http://hasura/v1/graphql"
  NLP_URL: "https://serving-ml.fabrique.social.gouv.fr"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  SOURCE_CONTAINER_COPY: "cdtn"
  DESTINATION_CONTAINER_COPY: "cdtn"
  SITEMAP_DESTINATION_CONTAINER: "sitemap"
  SITEMAP_DESTINATION_NAME: "sitemap.xml"
  SITEMAP_ENDPOINT: "http://www/api/sitemap"
  ELASTICSEARCH_INDEX_PREPROD: "cdtn-preprod-v1"
  ELASTICSEARCH_INDEX_PROD: "cdtn-prod-v1"
