name: Preproduction

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  group: pre-production
  cancel-in-progress: true

jobs:
  register:
    name: Register images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "cdtn-admin-frontend"
            path: "./targets/frontend"
            context: "."
          - images: "cdtn-admin-hasura"
            path: "./targets/hasura"
            context: "./targets/hasura"
          - images: "cdtn-admin-ingester"
            path: "./targets/ingester"
            context: "."
          - images: "cdtn-admin-alert-cli"
            path: "./targets/alert-cli"
            context: "."
          - images: "cdtn-admin-export-elasticsearch"
            path: "./targets/export-elasticsearch"
            context: "."
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imagePackage: ${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile"
          dockercontext: "${{ matrix.context }}"
          environment: preprod

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: preproduction
      url: https://preprod-cdtn-admin.dev.fabrique.social.gouv.fr/
    steps:
      - uses: SocialGouv/kube-workflow@master
        with:
          environment: preprod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
