name: Review

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  register:
    name: Register images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "cdtn-admin-frontend"
            path: "./targets/frontend"
            context: "."
          - images: "cdtn-admin-hasura"
            path: "./targets/hasura"
            context: "./targets/hasura"
          - images: "cdtn-admin-ingester"
            path: "./targets/ingester"
            context: "."
          - images: "cdtn-admin-alert-cli"
            path: "./targets/alert-cli"
            context: "."
          - images: "cdtn-admin-export-elasticsearch"
            path: "./targets/export-elasticsearch"
            context: "."
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          project: "cdtn-admin"
          imagePackage: ${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile"
          dockercontext: "${{ matrix.context }}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/kube-workflow@master
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
