name: Review

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  register:
    name: Register images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "cdtn-admin-frontend"
            path: "./targets/frontend"
            context: "."
          - images: "cdtn-admin-hasura"
            path: "./targets/hasura"
            context: "./targets/hasura"
          - images: "cdtn-admin-ingester"
            path: "./targets/ingester"
            context: "."
          - images: "cdtn-admin-ingester-elasticsearch"
            path: "./targets/ingester-elasticsearch"
            context: "."
          - images: "cdtn-admin-alert-cli"
            path: "./targets/alert-cli"
            context: "."
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          project: "cdtn-admin"
          imageName: cdtn-admin/${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile.github"
          dockercontext: "${{ matrix.context }}"

  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:
      - name: Install
        shell: bash
        run: |
          yarn add @socialgouv/kosko-charts
      - name: Get k8s infos
        id: k8s
        shell: bash
        run: |
          RAW_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          BRANCH=$(npx @socialgouv/env-slug "${RAW_BRANCH}")
          echo "::set-output name=branch::$(echo ${BRANCH})"
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "dev"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register, manifests]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
