name: Security vulnerability scanner

on:
  push:
    branches: ["master"]

concurrency:
  cancel-in-progress: true
  group: security-${{ github.ref }}

jobs:
  register:
    name: Register images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - images: "cdtn-admin-frontend"
            path: "./targets/frontend"
            context: "."
          - images: "cdtn-admin-hasura"
            path: "./targets/hasura"
            context: "./targets/hasura"
          - images: "cdtn-admin-ingester"
            path: "./targets/ingester"
            context: "."
          - images: "cdtn-admin-ingester-elasticsearch"
            path: "./targets/ingester-elasticsearch"
            context: "."
          - images: "cdtn-admin-alert-cli"
            path: "./targets/alert-cli"
            context: "."
    steps:
      - name: Register docker images
        uses: SocialGouv/actions/autodevops-build-register@local-cache-cdtn
        with:
          project: "cdtn-admin"
          imageName: cdtn-admin/${{ matrix.images }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.path }}/Dockerfile.github"
          dockercontext: "${{ matrix.context }}"

  trivy:
    name: Run trivy
    runs-on: ubuntu-18.04
    needs: [register]
    strategy:
      fail-fast: false
      matrix:
        images:
          [
            "cdtn-admin-frontend",
            "cdtn-admin-hasura",
            "cdtn-admin-ingester",
            "cdtn-admin-ingester-elasticsearch",
            "cdtn-admin-alert-cli",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ${{ matrix.images }} from Dockerfile
        run: |
          docker build -t ghcr.io/socialgouv/cdtn-admin/${{ matrix.images }}:sha-${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/socialgouv/cdtn-admin/${{ matrix.images }}:sha-${{ github.sha }}"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
