name: Gitlab mirroring

on:
  - push
  - delete

jobs:
  mirror_gitlab:
    name: 🪞 Gitlab
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/mirror-gitlab@v1
        with:
          project: SocialGouv/cdtn-admin
          token: ${{ secrets.SOCIALGROOVYBOT_GITLAB_TOKEN }}
